"""Computes every number and result table of the manuscript -> ../results.json. Figures are drawn by figures.py from results.json.

    python run_all.py        (about 25 minutes; each block prints as it finishes)
"""
import json
import os
import sys
import time

import numpy as np
from scipy.optimize import brentq, least_squares
from scipy.stats import norm

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import core as C            # noqa: E402
import numerics as N        # noqa: E402
import theory as T          # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
RES = {}
t0 = time.time()
n_ord, eps_fk = C.N_EXP, 3e-3
K = 801
zq = norm.ppf((np.arange(K) + 0.5) / K)


def rates(T_C):
    return float(T.arrhenius(C.A1, C.EA1, T_C)), float(T.arrhenius(C.A2, C.EA2, T_C)), float(T.arrhenius(C.A_REL, C.EA_REL, T_C))


def log(msg):
    print("[%5.0f s] %s" % (time.time() - t0, msg), flush=True)


# ================================================================== E1  availability clock (Proposition 1)
rows = []
for Tinf in (125.0, 140.0, 155.0):
    a, b, kr = rates(Tinf)
    num = C.integrate([Tinf], tau_th=1e9, width=0.5, p=dict(dtad=0.0), T0_off=0.0, dt=0.01, tmax=300.0)
    for al, key in ((0.1, "t10"), (0.5, "t50"), (0.9, "t90")):
        th = T.t_gated(al, a, b, n_ord, kr)
        rows.append(dict(T=Tinf, alpha=al, numeric=float(num[key][0]), clock=float(th), iso=T.t_iso(al, a, b, n_ord), tau_release=1.0 / kr))
RES["clock"] = rows
log("E1 clock: max relative error %.4f %%" % (100 * max(abs(r["clock"] - r["numeric"]) / r["numeric"] for r in rows)))

# ================================================================== E2  isothermal closed forms (Proposition 2)
rows = []
for Tinf in (110.0, 125.0, 140.0, 155.0):
    a, b, kr = rates(Tinf)
    for n in (1.0, 1.5):
        r = C.integrate([Tinf], tau_th=1e9, gated=False, p=dict(dtad=0.0, n=n), T0_off=0.0, dt=0.01, tmax=600.0)
        t10, t90 = float(r["t10"][0]), float(r["t90"][0])
        c10, c90 = T.t_iso(0.1, a, b, n), T.t_iso(0.9, a, b, n)
        rows.append(dict(T=Tinf, n=n, a=a, b=b, ratio=b / a, t10_num=t10, t90_num=t90, t10_th=c10, t90_th=c90, S_num=(t90 - t10) / t10, S_th=(c90 - c10) / c10,
                         S_law=float(T.sharpness_law(a, b)), t10_n1=float(T.t_iso_n1(0.1, a, b))))
RES["isothermal"] = rows
log("E2 isothermal: max rel. error of t10, t90 (exact quadrature) %.4f %%" % (100 * max(max(abs(r["t10_th"] - r["t10_num"]) / r["t10_num"], abs(r["t90_th"] - r["t90_num"]) / r["t90_num"]) for r in rows)))

# ================================================================== E3  storage leakage and design rule (Proposition 3)
T_STORAGE_MIN = 150.0
rows = []
for margin in (3.0, 6.0, 10.0):
    Ts = 118.0 - margin
    a, b, kr = rates(Ts)
    for sg in (2.0, 4.0, 6.0, 10.0):
        num = float(C.integrate([Ts], Tmelt=118.0, width=0.5, off=sg * zq, dt=0.05, T0_off=0.0)["a_end"][0])
        f = T.f_active(margin, sg)
        rows.append(dict(margin=margin, sigma=sg, f=f, numeric=num, analytic=float(T.leak(f, a, b, kr, T_STORAGE_MIN))))
RES["leakage"] = rows
log("E3 leakage: median ratio analytic/numeric %.3f" % np.median([r["analytic"] / r["numeric"] for r in rows if r["numeric"] > 1e-5]))

rows = []
for margin in (3.0, 6.0, 10.0):
    Ts = 118.0 - margin
    a, b, kr = rates(Ts)
    for eps in (0.001, 0.01, 0.05):
        s_an = T.sigma_star(eps, margin, a, b, kr, T_STORAGE_MIN)
        fnum = lambda sg: float(C.integrate([Ts], Tmelt=118.0, width=0.5, off=sg * zq, dt=0.05, T0_off=0.0)["a_end"][0]) - eps
        try:
            s_num = brentq(fnum, 0.3, 40.0, xtol=1e-3) if fnum(40.0) > 0 else None
        except ValueError:
            s_num = None
        rows.append(dict(margin=margin, eps=eps, sigma_star_analytic=None if not np.isfinite(s_an) else s_an, sigma_star_numeric=s_num, f_star=float(T.f_star(eps, a, b, kr, T_STORAGE_MIN))))
        log("   margin %.0f eps %.3f: sigma* analytic %s numeric %s" % (margin, eps, "no limit" if not np.isfinite(s_an) else "%.3f" % s_an, "n/a" if s_num is None else "%.3f" % s_num))
RES["design_rule"] = rows

# ---- synthetic-data recovery of (T_m, sigma) from isothermal storage curves
rng = np.random.default_rng(20261007)
true_sigma, true_Tm = 5.0, 118.0
times = np.array([30.0, 60.0, 90.0, 120.0, 150.0])
temps = [112.0, 108.0, 105.0]
noise = 0.002


def model_curves(sg, Tm):
    out = []
    for Ts in temps:
        a, b, kr = rates(Ts)
        f = T.f_active(Tm - Ts, sg)
        out.extend(T.leak(f, a, b, kr, t) for t in times)
    return np.array(out)


truth = model_curves(true_sigma, true_Tm)
# the "measurements" are generated by the full population ODE, not by the closed form used for the fit
meas0 = []
for Ts in temps:
    for t in times:
        meas0.append(float(C.integrate([Ts], Tmelt=true_Tm, width=0.5, off=true_sigma * zq, dt=0.05, T0_off=0.0, tmax=t)["a_end"][0]))
meas0 = np.array(meas0)
est = []
for k in range(200):
    y = np.clip(meas0 + noise * rng.standard_normal(meas0.size), 0, None)
    fit = least_squares(lambda p: (model_curves(p[0], p[1]) - y) / noise, x0=[3.0, 117.0], bounds=([0.5, 112.0], [15.0, 124.0]))
    est.append(fit.x)
est = np.array(est)
RES["recovery"] = dict(true_sigma=true_sigma, true_Tm=true_Tm, noise=noise, n_trials=len(est), times=times.tolist(), temps=temps,
                       sigma_mean=float(est[:, 0].mean()), sigma_sd=float(est[:, 0].std()), Tm_mean=float(est[:, 1].mean()), Tm_sd=float(est[:, 1].std()),
                       corr=float(np.corrcoef(est[:, 0], est[:, 1])[0, 1]), estimates=est[::5].tolist(),
                       noiseless_closed_form_vs_ode_max_abs_diff=float(np.max(np.abs(truth - meas0))))
log("E3b recovery: sigma %.2f +/- %.2f (true %.1f); Tm %.2f +/- %.2f (true %.1f); corr %.2f" % (est[:, 0].mean(), est[:, 0].std(), true_sigma, est[:, 1].mean(), est[:, 1].std(), true_Tm, RES["recovery"]["corr"]))

# ---- same recovery with a calorimetric prior on the mean melting temperature (0.5 C)
est2 = []
rng2 = np.random.default_rng(20261008)
for k in range(200):
    y = np.clip(meas0 + noise * rng2.standard_normal(meas0.size), 0, None)
    fit = least_squares(lambda p: np.concatenate([(model_curves(p[0], p[1]) - y) / noise, [(p[1] - true_Tm) / 0.5]]), x0=[3.0, 117.0], bounds=([0.5, 112.0], [15.0, 124.0]))
    est2.append(fit.x)
est2 = np.array(est2)
RES["recovery_prior"] = dict(Tm_prior_sd=0.5, sigma_mean=float(est2[:, 0].mean()), sigma_sd=float(est2[:, 0].std()), Tm_mean=float(est2[:, 1].mean()), Tm_sd=float(est2[:, 1].std()))
log("E3c recovery with Tm prior: sigma %.2f +/- %.2f" % (est2[:, 0].mean(), est2[:, 0].std()))

# ================================================================== E4  criticality (Proposition 4)
rows = []
for n in (1.0, 1.5, 2.0):
    for Th in (0.1, 0.03, 0.01, 0.003):
        rows.append(dict(n=n, Theta=Th, Pi_c_numeric=float(N.fk_critical(Th, n, eps_fk)), Pi_c0=float(T.Pi_c0(n, eps_fk))))
    log("E4 FK n=%.1f done" % n)
RES["critical_fk"] = rows
RES["critical_threshold_sensitivity"] = {str(thr): float(N.fk_critical(0.003, 1.5, eps_fk, thr=thr)) for thr in (0.15, 0.3, 0.6)}
RES["epsilon_dependence"] = {str(e): dict(numeric=float(N.fk_critical(0.01, 1.5, e)), theory=float(T.Pi_c0(1.5, e))) for e in (1e-4, 1e-3, 1e-2)}
log("E4 FK threshold sensitivity %s" % RES["critical_threshold_sensitivity"])

rows = []
for Th in (0.01, 0.003):
    for Pi in (0.5, 1.0, 1.5, 1.8):
        rows.append(dict(Theta=Th, Pi=Pi, numeric=N.fk_peak(Pi, Th, 1.5, eps_fk), qss=T.theta_peak_qss(Pi, Th, 1.5, eps_fk)))
RES["overshoot_qss"] = rows
rows = []
Pc = T.Pi_c0(1.5, eps_fk)
Th = 0.002
for frac in (0.5, 0.8, 0.9, 0.95, 0.98):
    Pi = frac * Pc
    rows.append(dict(frac=frac, psi_theta_numeric=float(N.fk_peak(Pi, Th, 1.5, eps_fk) * Pi / Th),
                     psi_theta_lambert=float(-1 * T.lambertw(-Pi / (np.e * Pc)).real), normal_form=float(T.exponent_form(Pi, 1.5, eps_fk))))
RES["fold_exponent"] = rows
log("E4 overshoot done")

rows = []
for Tinf in (120.0, 140.0, 160.0):
    a, b, kr = rates(Tinf)
    for Th in (0.01, 0.03, 0.1):
        tau = Th / b
        cr = N.arr_critical(Tinf, tau)
        fk = N.fk_critical(Th, 1.5, a / b)
        gated = N.arr_critical(Tinf, tau, gated_tau_rel=1.0 / kr) if Th == 0.03 else None
        rows.append(dict(T=Tinf, Theta=Th, tau_th=tau, Ar=cr["Ar"], eps=a / b, Pi_c_arrhenius=cr["Pi_c"], Pi_c_fk=float(fk), prediction=float(fk * T.arrhenius_factor(cr["Ar"])),
                         Pi_c_gated=None if gated is None else gated["Pi_c"], tau_release=1.0 / kr))
        log("   Arrhenius T=%.0f Theta=%.2f: Pi_c %.3f  (FK %.3f x e^(1/Ar) = %.3f)" % (Tinf, Th, cr["Pi_c"], fk, fk * T.arrhenius_factor(cr["Ar"])))
RES["critical_arrhenius"] = rows

# ================================================================== E5  continuous-flow reactor (Proposition 5)
eps, n = eps_fk, 1.5
vt = 1.0
res5 = {"kappa_c": T.kappa_c(eps, n)[0], "n": n, "eps": eps, "vartheta": vt}
cases = []
for psi in (3.0, 4.5, 20.0):
    kap = T.kappa(psi, vt)
    A0, Dd, Du = T.static_loop_area(eps, n, kap)
    lo_, hi_ = (np.log(Dd) - 2.0, np.log(Du) + 2.0) if Dd else (-4.0, 2.0)
    pts = []
    for v in (0.05, 0.02, 0.01, 0.005):
        a_, ju, jd = N.flow_sweep(v, lo_, hi_, psi, vt, n, eps)
        pts.append(dict(v=v, area=a_, jump_up=ju, jump_down=jd))
    v1, v2, a1, a2 = pts[-2]["v"], pts[-1]["v"], pts[-2]["area"], pts[-1]["area"]
    extrap = a2 - (a1 - a2) / (v1 - v2) * v2
    cases.append(dict(psi=psi, kappa=kap, bistable=bool(Dd), static_area=A0, lnD_down=None if not Dd else float(np.log(Dd)), lnD_up=None if not Du else float(np.log(Du)),
                      sweeps=pts, extrapolated_area=float(extrap)))
    log("E5 psi=%.1f kappa=%.2f static area %.3f extrapolated %.3f" % (psi, kap, A0, extrap))
res5["cases"] = cases
RES["flow"] = res5

json.dump(RES, open(os.path.join(HERE, "..", "results.json"), "w", encoding="utf-8"), indent=1, default=float)
log("done")
